package net.paulhertz.scanner;

public class HilbertGen extends PixelMapGen {
	/*
	 * See instance variables used or generated by this class in abstract class PixelMapGen.
	 */

	public final static String description = "HilbertGen generates Hilbert curve over a square bitmap starting at (0,0) and ending at (width-1, 0). "
			   + "Width and height must be equal powers of 2.";


	public HilbertGen(int width, int height) {
		super(width, height);
	}

	@Override
	public String describe() {
		return HilbertGen.description;
	}

	@Override
	public boolean validate(int width, int height) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int[] generate() {
		// TODO Auto-generated method stub
		return null;
	}


	/* ------------------------------ GETTERS AND NO SETTERS ------------------------------ */
	/*                                                                                      */
	/*                  See abstract class PixMapGen for additional methods                 */
	/*                                                                                      */
	/* These include: getWidth(), getHeight(), getSize(), getPixelMap(), getPixelMapCopy(), */
	/* getSampleMap(), get SampleMapCopy(), getCoordinates(), getCoordinatesCopy().         */
	/*                                                                                      */
	/* ------------------------------------------------------------------------------------ */


}
